# Generated by Django 6.0 on 2025-12-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0002_rename_titel_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cretaed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
