# Generated by Django 6.0 on 2026-01-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='brith_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
